<a href="https://colab.research.google.com/github/szeshiang/myrepo/blob/main/Exp1_tensors_24_Feb_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors**

In [2]:
import tensorflow as tf
import numpy as np

In [4]:
# step 1 - zero rank tensor-
tensor1=tf.constant(4)
print(tensor1)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
!pip install tensorflow

In [6]:
# create rank one tensor (similar to a 1-D array)
tensor_rank1=tf.constant([2.0,9.0,7.0])
tensor_rank1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 9., 7.], dtype=float32)>

In [8]:
# create rank two tensor / matrix
tensor_rank2=tf.constant([[0,1,2],[2,3,4],[4,5,6]])
tensor_rank2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]], dtype=int32)>

In [9]:
# convert to numpy array
tensor_rank2.numpy()

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]], dtype=int32)

In [10]:
# perform mathematical operations on tensors
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
print(tf.add(a,b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [11]:
print(tf.multiply(a,b))

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [12]:
b=tf.constant([[5,6],[7,8]])
print(tf.reduce_max(b))

tf.Tensor(8, shape=(), dtype=int32)


In [13]:
print(tf.math.argmax(b))

tf.Tensor([1 1], shape=(2,), dtype=int64)


In [14]:
# broadcasting in tensors
x=tf.constant([1,2,3])
y=tf.constant(2)
print(tf.multiply(x,2))
print(tf.multiply(x,y))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [17]:
# reshape the tensor
b=tf.constant([[5,6,6],[7,8,9]])
print(b.shape)

(2, 3)


**Ragged Tensor**
- used when there are variable number of elements along some axes
- ragged is used to create a rectangular shape. dun need to use if list is already in a proper shape or has same number of elements

In [18]:
list1=[[3,4,5],[5],[6,7]]
tensor4=tf.ragged.constant(list1)
tensor4

<tf.RaggedTensor [[3, 4, 5], [5], [6, 7]]>

In [19]:
list0=[[2,3,4],[4,5,6]]
tensor0=tf.constant(list0)
tensor0

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [4, 5, 6]], dtype=int32)>

In [20]:
tensor4.shape

TensorShape([3, None])

In [23]:
tensor4.ragged_rank

1

In [21]:
tensor0.shape

TensorShape([2, 3])

In [27]:
tensor0.ndim

2

In [31]:
list2=[[[3,4],[5]],[[4],[5,6,7]]]
tensor2=tf.ragged.constant(list2)
tensor2

<tf.RaggedTensor [[[3, 4], [5]],
 [[4], [5, 6, 7]]]>

In [32]:
tensor2.ragged_rank

2